import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[window]
decorations = "none"
startup_mode = "Maximized"
title = "Terminal"
opacity = 0.95

[window.padding]
x = 3
y = 3
