palette = "github_dark_dimmed"

format = '$directory$character' 
right_format = '$git_branch$git_status$kubernetes$azure$python'
add_newline = false

[palettes.github_dark_dimmed]
# red = '#ff938a'
red = '#f47067'
green = '#6bc46d'
yellow = '#ddad43'
blue = '#6cb6ff'
magenta = '#b083f0'
cyan = '#39c5cf'
white = '#909dab'
grey = "#626880"

[azure]
disabled = false
symbol = '󰠅 '
style = 'bg:panel fg:blue bold'
format = ' [\[($symbol$subscription)\]]($style)'

[character]
success_symbol = "[▶](grey)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[N](bold green)"
vimcmd_replace_symbol = "[R](red)"
vimcmd_visual_symbol = "[V](yellow)"

[directory]
read_only = " ro"
format = '[\[$path\]](grey) '

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
style = "bg:panel fg:red bold"
format = '( [\[$all_status$ahead_behind\]]($style))'

[git_branch]
symbol = "git "
style = "bg:panel fg:yellow bold"
format = '[\[$branch\]]($style)'

[python]
symbol = "py "
format = ' ([\[$virtualenv\]](green))'

[kubernetes]
#format = '[($user on )($cluster in )$context \($namespace\)](dimmed green) '
# format = ' [\[$context\]](#92B3DE)'
format = ' [\[$context\]](purple)'
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'gke_.*_(?P<var_cluster>[\w-]+)' = 'gke-$var_cluster'
[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'

[time]
disabled = false
format = ' [\[$time\]](grey)'
time_format = '%T'
utc_time_offset = '+2'
