palette = "catppuccin_frappe"

format = '$directory$character' 
right_format = '$git_branch$git_status$kubernetes$azure$python'
add_newline = false

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[azure]
disabled = false
symbol = '󰠅 '
format = ' [\[($subscription)\]](blue)'

[character]
success_symbol = "[▶](surface2)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[N](bold green)"
vimcmd_replace_symbol = "[R](red)"
vimcmd_visual_symbol = "[V](yellow)"

[directory]
read_only = " ro"
format = '[\[$path\]](surface2) '

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
format = '( [\[$all_status$ahead_behind\]]($style))'

[git_branch]
symbol = "git "
format = '[\[$branch\]](yellow)'

[python]
symbol = "py "
format = ' ([\[$virtualenv\]](green))'

[kubernetes]
#format = '[($user on )($cluster in )$context \($namespace\)](dimmed green) '
# format = ' [\[$context\]](#92B3DE)'
format = ' [\[$context\]](purple)'
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'gke_.*_(?P<var_cluster>[\w-]+)' = 'gke-$var_cluster'
[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'

[time]
disabled = false
format = ' [\[$time\]](surface2)'
time_format = '%T'
utc_time_offset = '+2'
